name: Go Release

on:
  release:
    types: [created]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [arm64, amd64]
        exclude:
          - goarch: arm64
            goos: linux
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.52
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion:  1.22.8
          binary_name: "nomad-dotnet-driver"
          extra_files: LICENSE README.md